services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack-local
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - SERVICES=s3,dynamodb
      - DEBUG=${DEBUG- }
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "./scripts:/etc/localstack/init/ready.d"
      - "../music-streaming-ui:/tmp/ui-source"
      - "/Users/michaelburgess/Personal/mymusic:/tmp/music-source"
    networks:
      - service_net
  DynamoDbGui:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb-admin-personal
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4569
    depends_on:
      - localstack
    networks:
      - service_net
networks:
  service_net:
    driver: bridge