version: '3.2'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack-local-personal
    ports:
      - "4567-4597:4567-4597"
      - "${PORT_WEB_UI-8044}:${PORT_WEB_UI-8080}"
    environment:
      - SERVICES=s3,dynamodb
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - '/Users/michaelburgess/Documents/localstack:/tmp/localstack'
    networks:
      - service_net
  DynamoDbGui:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb-admin-personal
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4569
    depends_on:
      - localstack
    networks:
      - service_net
networks:
  service_net:
    driver: bridge
