spring.profiles.active=local
aws.dynamodb.endpoint=http://localhost:4566
aws.region=us-east-2
aws.s3.bucket=music-streaming-storage
#aws.s3.endpoint=http://localhost:4566
spring.main.allow-bean-definition-overriding=true
music.local.path=/Users/michaelburgess/Personal/mymusic/
spring.jackson.serialization.write-dates-as-timestamps=false
